import { DM_Sans } from "next/font/google";
import "./globals.css";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Chat-Ayna",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-200 md:p-5 w-full h-screen`}>
        <main className=" w-full h-full">{children}</main>
      </body>
    </html>
  );
}
